source "https://rubygems.org"

gem "jekyll", "~> 4.1.1"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
# gem "jekyll-target-blank"
gem "jemoji"
gem "jekyll-compose"
gem "capistrano", "~> 2"
gem "rake"
